//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paypart_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Classes = new HashSet<Class>();
            this.Terms = new HashSet<Term>();
            this.Phones = new HashSet<Phone>();
            this.Emails = new HashSet<Email>();
            this.Addresses = new HashSet<Address>();
            this.Fees = new HashSet<Fee>();
        }
    
        public long id { get; set; }
        public long typeid { get; set; }
        public string name { get; set; }
        public string logo { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
        public virtual OrganizationType OrganizationType { get; set; }
        public virtual ICollection<Term> Terms { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
    }
}
