//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paypart_admin.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ServiceAccount
    {
        public long id { get; set; }
        public int serviceid { get; set; }
        public string bankcode { get; set; }
        public string bankname { get; set; }
        public string accountnumber { get; set; }
        public string accountname { get; set; }
        public string accountref { get; set; }
        public int status { get; set; }
    }
}
