//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paypart_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int _id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public int billerid { get; set; }
        public System.DateTime datecreated { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
        public string createdby { get; set; }
        public string token { get; set; }
        public int status { get; set; }
    
        public UserRole role { get; set; }
    }
}
